// Activité « Dentiste » : terminologie et tableau de bord spécifiques.
export default async ({ page, shot, log }) => {
  await page.getByText('Bienvenue sur DigiPlan').waitFor({ timeout: 30_000 })
  await page.getByRole('button', { name: /Commencer la configuration/ }).click()
  await page.getByRole('button', { name: /Dentiste/ }).click()
  await page.getByRole('button', { name: /Continuer/ }).click()
  await page.locator('#b-name').fill('Cabinet Dentaire Al Amal')
  await page.locator('#b-owner').fill('Dr Imane Tazi')
  await page.getByRole('button', { name: /Continuer/ }).click()
  await page.getByRole('button', { name: /Continuer/ }).click()
  await page.getByRole('button', { name: /Continuer/ }).click()
  await page.getByText('Vos soins').waitFor()
  await shot('dentist-services')
  await page.getByRole('button', { name: /Terminer la configuration/ }).click()
  await page.getByRole('button', { name: /Commencer avec DigiPlan/ }).click()
  await page.getByText('Prochain rendez-vous').first().waitFor({ timeout: 15_000 })
  await page.waitForTimeout(800)
  await shot('dentist-dashboard')
  await page.keyboard.press('Control+Shift+C')
  await page.waitForTimeout(500)
  await shot('dentist-patient-form')
  const nav = await page.getByRole('navigation', { name: 'Navigation principale' }).innerText()
  log('navigation :', nav.replace(/\s+/g, ' | '))
}
